"""
Django settings for distribuidor_dj project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""


from .base import *  # noqa

# read environment files
ENV_DIR = BASE_DIR / "envs" / "dev"  # noqa F405
env.read_env(str(ENV_DIR / "django"))  # noqa F405
env.read_env(str(ENV_DIR / "postgres"))  # noqa F405

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# https://docs.djangoproject.com/en/stable/ref/settings/#databases
DATABASES = {"default": env.db("DATABASE_URL")}
DATABASES["default"]["ATOMIC_REQUESTS"] = True

ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "host.docker.internal"]


# If use HMR or not.
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_DEV_SERVER_PROTOCOL = "https"


# https://github.com/benoitc/gunicorn/issues/1562#issuecomment-1530850143
# Gunicorn worker will have cached templates, so disable them in development
TEMPLATES[0]["OPTIONS"]["loaders"] = default_loaders

# WAGTAILADMIN_BASE_URL required for notification emails
WAGTAILADMIN_BASE_URL = "https://127.0.0.1:8000"

# https://pypi.org/project/django-cors-headers/
CORS_ALLOW_ALL_ORIGINS = False

# Serve static and media files staticfiles
MIDDLEWARE.insert(3,"whitenoise.middleware.WhiteNoiseMiddleware")

CORS_ALLOWED_ORIGINS = [
    "https://127.0.0.1:8000",
    "https://localhost:8000",
    "https://django:8000",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
