# Generated by Django 4.2.3 on 2023-08-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_text', models.CharField(help_text='Texto introductorio de la página promocional', max_length=255)),
                ('header_cta', models.CharField(help_text='Texto del Botón de registrarse', max_length=255, verbose_name='Botón de registrarse')),
                ('hero_one_title', models.CharField(max_length=255, verbose_name='Titulo del primer factor promocional')),
                ('hero_one_desc', models.TextField(verbose_name='Descripción del primer factor promocional')),
                ('header_image', models.ForeignKey(blank=True, help_text='Logo de la cabecera del home', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_one_image', models.ForeignKey(blank=True, help_text='Imagen del primer factor promocional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
