# Generated by Django 4.2.10 on 2024-02-28 01:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wagtail_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'h2', 'h3', 'h4'])), ('image', wagtail.images.blocks.ImageChooserBlock())], verbose_name='Contenido del blog'),
        ),
    ]
