# Generated by Django 5.0.6 on 2024-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_news_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventpage",
            options={"verbose_name": "Evento"},
        ),
        migrations.AlterModelOptions(
            name="newspage",
            options={"verbose_name": "Noticia"},
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="description",
            field=models.CharField(
                help_text="Descripción corta de sobre el evento",
                max_length=255,
                verbose_name="Descripción breve",
            ),
        ),
    ]
