# Generated by Django 5.0.6 on 2024-10-26 21:15

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django_src.settings.wagtail_pages import MENTORS_GROUP_NAME, pro_carreer_index_path

def initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Permission = apps.get_model("auth", model_name="Permission")
    Group = apps.get_model("auth", model_name="Group")
    GroupPagePermission = apps.get_model("wagtailcore", model_name="GroupPagePermission")
    ProCarreerIndex = apps.get_model("pro_carreer", model_name="ProCarreerIndex")

    # Get the mentores group
    mentor_group = Group.objects.get(name=MENTORS_GROUP_NAME)
    pro_career_index = ProCarreerIndex.objects.get(path=pro_carreer_index_path)
    add_page_permission = Permission.objects.get(codename="add_page")
    change_page_permission = Permission.objects.get(codename="change_page")

    GroupPagePermission.objects.create(
        group=mentor_group, page=pro_career_index,
        permission=add_page_permission,
    )

    GroupPagePermission.objects.create(
        group=mentor_group, page=pro_career_index,
        permission=change_page_permission,
    )

def remove_initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Permission = apps.get_model("auth", model_name="Permission")
    Group = apps.get_model("auth", model_name="Group")
    GroupPagePermission = apps.get_model("wagtailcore", model_name="GroupPagePermission")
    ProCarreerIndex = apps.get_model("pro_carreer", model_name="ProCarreerIndex")

    mentor_group = Group.objects.get(name=MENTORS_GROUP_NAME)
    pro_career_index = ProCarreerIndex.objects.get(path=pro_carreer_index_path)
    add_page_permission = Permission.objects.get(codename="add_page")
    change_page_permission = Permission.objects.get(codename="change_page")

    p1 = GroupPagePermission.objects.get(
        group=mentor_group, page=pro_career_index,
        permission=add_page_permission,
    )

    p2 = GroupPagePermission.objects.get(
        group=mentor_group, page=pro_career_index,
        permission=change_page_permission,
    )

    p1.delete()
    p2.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_meta_options"),
        ("pro_carreer", "0002_setup_professions"),
        # change_page, and add_page Admin datafixtures are created here
        ('wagtailadmin', '0003_admin_managed'),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data)
    ]
