# Generated by Django 5.0.6 on 2024-10-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentor", "0002_mentorshiphistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mentorship",
            options={"verbose_name": "Mentoría", "verbose_name_plural": "Mentorías"},
        ),
        migrations.AlterModelOptions(
            name="mentorshiphistory",
            options={
                "verbose_name": "Historial de mentoría",
                "verbose_name_plural": "Historial de mentorías",
            },
        ),
        migrations.AlterModelOptions(
            name="mentorshiprequest",
            options={
                "verbose_name": "Solicitud de mentoría",
                "verbose_name_plural": "Solicitudes de mentoría",
            },
        ),
        migrations.AlterModelOptions(
            name="studentmentorshiptask",
            options={
                "verbose_name": "Tarea de mentoría de estudiantes",
                "verbose_name_plural": "Tareas de mentoría de estudiantes",
            },
        ),
    ]
