# Generated by Django 4.2.7 on 2024-01-07 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('register', '0001_squashed_0004_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProCarreerIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProfessionalCarreer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(max_length=250, verbose_name='Descripción corta')),
                ('content', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True)),
                ('image', models.ForeignKey(blank=True, help_text='Imagen del factor promocional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen para la descripción corta')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProCarreerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Experiencia')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('init_year', models.DateField(verbose_name='Año inicio')),
                ('end_year', models.DateField(blank=True, null=True, verbose_name='Año fin')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_career_experiences', to='register.mentor', verbose_name='Mentor')),
                ('pro_carreer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_experiences', to='pro_carreer.professionalcarreer', verbose_name='Carrera profesional')),
            ],
        ),
    ]
