# Generated by Django 4.2.7 on 2024-01-13 17:26

from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.conf import settings

from django.db import migrations

from django.utils.translation import gettext_lazy as _

pro_carreer_index_path = "0003"

def pro_carreer_index(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):

    # get_user_model doesn't works in data migrations because it sets required_ready to False
    User = apps.get_model(settings.AUTH_USER_MODEL)

    Page = apps.get_model("wagtailcore", model_name="Page")
    ProCarreerIndex = apps.get_model("pro_carreer", model_name="ProCarreerIndex")
    ContentType = apps.get_model("contenttypes.ContentType")

    # Admin is Created by 0002_setup_admin
    admin = User.objects.get(username=settings.ADMIN_USERNAME)

    # Root page is created by wagtail's data migrations
    root_page = Page.objects.get(slug='root')

    page_content_type = ContentType.objects.get_for_model(ProCarreerIndex)

    # Create the pro carreer index page
    ProCarreerIndex.objects.create(
        title=_("Carreras profesionales"),
        owner=admin,
        content_type=page_content_type,
        locale=root_page.locale,
        slug="profesiones",
        url_path="/profesiones/",
        # Tree beard low level data
        depth=2,
        numchild=0,
        # How do I know it is the third child ? See variable home_page_path on file
        # on django_src/apps/main/migrations/0003_wagtail_setup.py
        path=root_page.path + "0003",
    )

def remove_pro_carreer_index(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Page = apps.get_model("wagtailcore", model_name="Page")
    ProCarreerIndex = apps.get_model("pro_carreer", model_name="ProCarreerIndex")

    # Root page is created by wagtail's data migrations
    root_page = Page.objects.get(slug='root')

    # Delete the created index
    index = ProCarreerIndex.objects.get(path=root_page.path + "0003")
    index.delete()


class Migration(migrations.Migration):

    dependencies = [
        # To access wagtail's root page
        ('wagtailadmin', '0003_admin_managed'),

        # Admin user is created in this migration
        ('customauth', '0002_setup_admin'),

        # Home page is created on this migration
        ('main', '0003_wagtail_setup'),

        ('pro_carreer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(pro_carreer_index, remove_pro_carreer_index)
    ]
