# Generated by Django 4.2.9 on 2024-02-01 01:19

import django.core.validators
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_themespecprocarreer'),
        ('pro_carreer', '0002_setup_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='procarreerexperience',
            name='company',
            field=models.CharField(default='Yahoo', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionalcarreer',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'h2', 'h3', 'h4'])), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True, verbose_name='Contenido'),
        ),
        migrations.AlterUniqueTogether(
            name='procarreerexperience',
            unique_together={('pro_carreer', 'mentor')},
        ),
    ]
