# Generated by Django 5.0.6 on 2024-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pro_carreer", "0003_constrains_missingfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procarreerexperience",
            options={
                "verbose_name": "Experiencia de Carrera Profesional",
                "verbose_name_plural": "Experiencias de Carreras Profesionales",
            },
        ),
        migrations.AlterModelOptions(
            name="procarreerindex",
            options={
                "verbose_name": "Indice de carreras profesionales",
                "verbose_name_plural": "Indices de carreras profesionales",
            },
        ),
    ]
