# Generated by Django 5.0.6 on 2024-10-27 21:48

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django_src.settings.wagtail_pages import PROFESSORS_GROUP_NAME, events_index_path, professor_collection_path

def initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Permission = apps.get_model("auth", model_name="Permission")
    Group = apps.get_model("auth", model_name="Group")
    EventsIndex = apps.get_model("main", model_name="EventsIndex")
    GroupPagePermission = apps.get_model("wagtailcore", model_name="GroupPagePermission")
    Collection = apps.get_model("wagtailcore", model_name="Collection")
    GroupCollectionPermission = apps.get_model("wagtailcore", model_name="GroupCollectionPermission")

    events_index = EventsIndex.objects.get(path=events_index_path)


    # Create a professors group
    professor_group = Group.objects.create(name=PROFESSORS_GROUP_NAME)

    # Professor group can access the wagtail admin interface
    wagtail_access_admin = Permission.objects.get(codename="access_admin")
    professor_group.permissions.add(wagtail_access_admin)

    # Setup page permissions for the professor_group groups
    # add_page comes from wagtail's data migrations
    add_page_permission = Permission.objects.get(codename="add_page")
    change_page_permission = Permission.objects.get(codename="change_page")
    unpublish_page_permission = Permission.objects.get(codename="unpublish_page")

    permissions_to_add = [add_page_permission, change_page_permission, unpublish_page_permission]

    for permission in permissions_to_add:
        GroupPagePermission.objects.create(
            group=professor_group, page=events_index,
            permission=permission,
        )

    # Create a collection for the professors
    professor_collection = Collection.objects.create(
        # Wagtail data
        name=PROFESSORS_GROUP_NAME,
        # Tree beard low level data
        path=professor_collection_path,
        depth=2,
        numchild=0,
    )

    # Add permissions to the professor group to add documents and images to the mentores collection
    add_document_permission = Permission.objects.get(codename="add_document")
    add_image_permission = Permission.objects.get(codename="add_image")

    change_image_permission = Permission.objects.get(codename="change_image")
    choose_image_permission = Permission.objects.get(codename="choose_image")
    change_document_permission = Permission.objects.get(codename="change_document")
    choose_document_permission = Permission.objects.get(codename="choose_document")
    collection_permissions = [add_document_permission, add_image_permission, change_image_permission, choose_image_permission, change_document_permission, choose_document_permission]

    for collection_permission in collection_permissions:
        GroupCollectionPermission.objects.create(
            group=professor_group, collection=professor_collection,
            permission=collection_permission,
        )

def remove_initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):

    Group = apps.get_model("auth", model_name="Group")
    Collection = apps.get_model("wagtailcore", model_name="Collection")

    professor_group = Group.objects.get(name=PROFESSORS_GROUP_NAME)

    professor_group.delete()
    professor_collection = Collection.objects.get(path=professor_collection_path)
    professor_collection.delete()

class Migration(migrations.Migration):

    dependencies = [
        ("professor", "0001_initial"),

        # access_admin, and add_page Admin datafixtures are created here
        ('wagtailadmin', '0003_admin_managed'),

        # To acces add_document permission
        ("wagtaildocs", "0012_uploadeddocument"),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data)
    ]
