# Generated by Django 4.2.7 on 2023-12-09 19:21

import os

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.contrib.auth import get_user_model


def initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    User = get_user_model()

    try:
        admin = User.objects.get(username=os.environ["ADMIN_USERNAME"])
    except User.DoesNotExist:
        admin = User.objects.create_superuser(
            username=os.environ["ADMIN_USERNAME"],
            password=os.environ["ADMIN_PASSWORD"],
        )
def remove_initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data)
    ]
