# Generated by Django 4.2.7 on 2024-01-05 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('register', '0001_initial'), ('register', '0002_voucher_field'), ('register', '0003_validators_uniqueness'), ('register', '0004_register_status')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='CarrerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Nombre')),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.carreer', verbose_name='Carrer')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='InterestTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='register.carreer', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.interesttheme', verbose_name='Tema de interés')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student', verbose_name='Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(through='register.StudentInterest', to='register.interesttheme', verbose_name='Intereses'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='register.carrerspecialization', verbose_name='Especialización'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carreer',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreers', to='register.faculty', verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='carreer',
            name='interest_themes',
            field=models.ManyToManyField(to='register.interesttheme', verbose_name='Temas de interés'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='register.carreer', verbose_name='Carrera')),
                ('students', models.ManyToManyField(to='register.student', verbose_name='Estudiantes mentoreados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.FileField(blank=True, null=True, upload_to='mentor_vouchers', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentores',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='student_vouchers', verbose_name='Comprobante de estudios'),
        ),
        migrations.CreateModel(
            name='MentorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Ej: Frontend developer', validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre del cargo')),
                ('company', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Compañía')),
                ('init_year', models.DateField(verbose_name='Año inicio')),
                ('end_year', models.DateField(blank=True, null=True, verbose_name='Año fin')),
                ('current', models.BooleanField(verbose_name='¿ Cargo actual ?')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Descripción del cargo')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='register.mentor', verbose_name='Experiencie Mentor')),
            ],
            options={
                'verbose_name': 'Experiencia profesional',
                'verbose_name_plural': 'Experiencias profesionales',
                'unique_together': {('mentor', 'name', 'company', 'init_year', 'end_year')},
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='mentor',
            name='students',
            field=models.ManyToManyField(blank=True, to='register.student', verbose_name='Estudiantes mentoreados'),
        ),
        migrations.CreateModel(
            name='RegisterApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(choices=[('WAITING', 'Esperando aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], verbose_name='Estatus')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_approvals', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Aprobación de registro',
                'verbose_name_plural': 'Aprobaciones de registro',
            },
        ),
    ]
