# Generated by Django 4.2.7 on 2023-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='mentor_vouchers', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='student',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='student_vouchers', verbose_name='Comprobante de estudios'),
        ),
    ]
