# Generated by Django 4.2.7 on 2023-11-29 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_voucher_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorexperience',
            options={'verbose_name': 'Experiencia profesional', 'verbose_name_plural': 'Experiencias profesionales'},
        ),
        migrations.AlterField(
            model_name='mentorexperience',
            name='company',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='mentorexperience',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Descripción del cargo'),
        ),
        migrations.AlterField(
            model_name='mentorexperience',
            name='name',
            field=models.TextField(help_text='Ej: Frontend developer', validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombre del cargo'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorexperience',
            unique_together={('mentor', 'name', 'company', 'init_year', 'end_year')},
        ),
    ]
