# Generated by Django 4.2.7 on 2024-01-04 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('register', '0003_validators_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentores'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='mentor',
            name='register_state',
            field=models.TextField(choices=[('WAITING', 'Esperando aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='WAITING', verbose_name='Estatus de Registro'),
        ),
        migrations.AddField(
            model_name='student',
            name='register_state',
            field=models.TextField(choices=[('WAITING', 'Esperando aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='WAITING', verbose_name='Estatus de Registro'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='students',
            field=models.ManyToManyField(blank=True, to='register.student', verbose_name='Estudiantes mentoreados'),
        ),
        migrations.CreateModel(
            name='RegisterApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(choices=[('WAITING', 'Esperando aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], verbose_name='Estatus')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_approvals', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Aprobación de registro',
                'verbose_name_plural': 'Aprobaciones de registro',
            },
        ),
    ]
