# Generated by Django 4.2.7 on 2023-12-09 14:31

from django.db import migrations

from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

app_label = "register"

def create_interest_themes(apps: Apps, carreer):
    """
    Create interest themes for a carrer
    """

    InterestTheme = apps.get_model(app_label, "InterestTheme")

    interests = InterestTheme.objects.bulk_create(
        [
            InterestTheme(name="Matemáticas"),
            InterestTheme(name="Programación"),
            InterestTheme(name="HTML"),
            InterestTheme(name="Javascript"),
            InterestTheme(name="CSS"),
            InterestTheme(name="C++"),
            InterestTheme(name="UI/UX"),
            InterestTheme(name="Trabajo en equipo"),
            InterestTheme(name="Gestion de Recursos"),
            InterestTheme(name="BPM"),
        ]
    )

    carreer.interest_themes.add(*interests)

def initial_data(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    Faculty = apps.get_model(app_label, "Faculty")

    agronomia, created = Faculty.objects.get_or_create(
        name="Agronomía",
    )

    agronomia.carreers.get_or_create(name="Agronomía")

    arquitectura, created = Faculty.objects.get_or_create(
        name="Arquitectura y Urbanismo",
    )

    arquitectura.carreers.get_or_create(name="Arquitectura")

    ciencias, created = Faculty.objects.get_or_create(
        name="Ciencias",
    )

    ciencias.carreers.get_or_create(name="Geoquímica")
    ciencias.carreers.get_or_create(name="Matemática")
    ciencias.carreers.get_or_create(name="Química")
    ciencias.carreers.get_or_create(name="Biología")
    computacion, created = ciencias.carreers.get_or_create(name="Computación")

    computacion_specialization =[
        "Aplicaciones Tecnología Internet",
        "Inteligencia artificial",
        "Base de datos",
        "Ingeniería de Software",
        "Computación Gráfica",
        "Sistemas de información",
        "Sistemas distribuidos y paralelos",
        "Calculo Científico",
        "Modelos matemáticos",
        "Tecnologías educativas",
        "Tecnologías en Comunicaciones y Redes de Computadoras"
    ]

    for carrerspecialization in computacion_specialization:
        computacion.carrerspecialization_set.get_or_create(
            name=carrerspecialization,
        )

    create_interest_themes(apps, computacion)

    ciencias.carreers.get_or_create(name="Física")

    faces, created = Faculty.objects.get_or_create(
        name="Ciencias Económicas y Sociales",
    )
    faces.carreers.get_or_create(name="Administración y Contaduría")
    faces.carreers.get_or_create(name="Antropología")
    faces.carreers.get_or_create(name="Estadística y Ciencias Actuariales")
    faces.carreers.get_or_create(name="Economía")
    faces.carreers.get_or_create(name="Estudios Internacionales")
    faces.carreers.get_or_create(name="Sociología")
    faces.carreers.get_or_create(name="Trabajo Social")

    derecho, created = Faculty.objects.get_or_create(
        name="Ciencias Jurídicas y Políticas",
    )

    veterinaria, created = Faculty.objects.get_or_create(
        name="Ciencias Veterinarias",
    )

    farmacia, created = Faculty.objects.get_or_create(
        name="Farmacia",
    )

    humanidades, created = Faculty.objects.get_or_create(
        name="Humanidades y Educación",
    )

    humanidades.carreers.get_or_create(name="Artes" )
    humanidades.carreers.get_or_create(name="Bibliotecología y Archivología")
    humanidades.carreers.get_or_create(name="Comunicación Social")
    humanidades.carreers.get_or_create(name="Educación")
    humanidades.carreers.get_or_create(name="Filosofía")
    humanidades.carreers.get_or_create(name="Geografía")
    humanidades.carreers.get_or_create(name="Historia")
    humanidades.carreers.get_or_create(name="Idiomas Modernos")
    humanidades.carreers.get_or_create(name="Letras")
    humanidades.carreers.get_or_create(name="Psicología")

    ingenieria = Faculty.objects.get_or_create(
        name="Ingeniería",
    )

    medicina = Faculty.objects.get_or_create(
        name="Medicina",
    )

    odontologia = Faculty.objects.get_or_create(
        name="Odontología",
    )

def remove_initial_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_validators_uniqueness'),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data)
    ]
