# Generated by Django 4.2.9 on 2024-01-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_carreer', '0002_setup_professions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('register', '0001_squashed_0004_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='register.carrerspecialization', verbose_name='Especialización'),
        ),
        migrations.CreateModel(
            name='ThemeSpecProCarreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pro_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_themespecs', to='pro_carreer.professionalcarreer', verbose_name='Carrera profesional')),
            ],
            options={
                'unique_together': {('pro_career', 'content_type', 'object_id')},
            },
        ),
    ]
