# Generated by Django 4.2.7 on 2024-01-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pro_carreer', '0001_initial'),
        ('register', '0001_squashed_0004_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSpecProCarreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('pro_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_themespecs', to='pro_carreer.professionalcarreer', verbose_name='Carrera profesional')),
            ],
        ),
    ]
