# Generated by Django 5.0.6 on 2024-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_themespecprocarreer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerapprovals",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
        ),
    ]
