# Generated by Django 5.0.6 on 2024-10-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_meta_options"),
        ("register", "0006_alter_registerapprovals_date"),
        ("student", "0001_student_job_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="applied_jobs",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="student.StudentJobOffer",
                to="business.joboffer",
                verbose_name="Trabajos aplicados",
            ),
        ),
    ]
