# Generated by Django 5.0.6 on 2025-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EgresadosData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefijo_cedula",
                    models.CharField(
                        choices=[
                            ("VENEZOLANO", "Venezolano"),
                            ("PASAPORTE", "Pasaporte"),
                            ("JURÍDICO", "Jurídico"),
                            ("EXTRANJERO", "Extranjero"),
                            ("GUBERNAMENTAL", "Gubernamental"),
                            ("COMUNA", "Comuna"),
                        ],
                        help_text="",
                        max_length=255,
                        verbose_name="Prefijo cédula",
                    ),
                ),
                (
                    "cedula",
                    models.PositiveIntegerField(help_text="", verbose_name="Cédula"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Segundo Nombre"
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Apellido"
                    ),
                ),
                (
                    "segundo_apellido",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Segundo Apellido"
                    ),
                ),
                (
                    "fecha_nac",
                    models.DateField(help_text="", verbose_name="Fecha nacimiento"),
                ),
                (
                    "ciudad",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Ciudad"
                    ),
                ),
                (
                    "pais_nac",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Pais nacimiento"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Estado"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Direccion"
                    ),
                ),
                (
                    "telefono_2",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Telefono 2",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        help_text="",
                        max_length=255,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Usuario"
                    ),
                ),
                (
                    "idafiliados",
                    models.PositiveIntegerField(
                        help_text="", verbose_name="Idafiliados"
                    ),
                ),
                (
                    "carnet",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Carnet",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Telefono"
                    ),
                ),
                ("celular", models.CharField(help_text="", verbose_name="Celular")),
                (
                    "fec_registro",
                    models.DateField(help_text="", verbose_name="Fecha Registro"),
                ),
                (
                    "fec_afiliacion",
                    models.DateField(
                        blank=True,
                        help_text="",
                        null=True,
                        verbose_name="Fecha Afiliacion",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Sin carnet"),
                            ("1", "Activo"),
                            ("otros", "Otros"),
                        ],
                        help_text="",
                        null=True,
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "pais",
                    models.CharField(help_text="", max_length=255, verbose_name="Pais"),
                ),
                (
                    "tipo_afiliacion",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Tipo Afiliacion"
                    ),
                ),
                (
                    "codigo_postal",
                    models.PositiveIntegerField(
                        help_text="", verbose_name="Codigo postal"
                    ),
                ),
                (
                    "empleado_ucv",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Empleado ucv"
                    ),
                ),
                (
                    "fac_empleado",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Facultad Empleado"
                    ),
                ),
                (
                    "otra_dependencia",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Otra dependencia",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        blank=True,
                        help_text="",
                        null=True,
                        verbose_name="Fecha Ingreso",
                    ),
                ),
                (
                    "egresado_pregrado_ucv",
                    models.CharField(
                        help_text="",
                        max_length=255,
                        verbose_name="Egresado pregrado ucv",
                    ),
                ),
                (
                    "titulo_pregrado_ucv",
                    models.CharField(
                        help_text="", max_length=255, verbose_name="Titulo pregrado ucv"
                    ),
                ),
                (
                    "universidad_pregrado_otra",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Universidad pregrado otra",
                    ),
                ),
                (
                    "fecha_egreso_pregrado_otra",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Fecha egreso pregrado otra",
                    ),
                ),
                (
                    "facultad_postgrado_ucv",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Facultad postgrado ucv",
                    ),
                ),
                (
                    "programa_postgrado",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Programa postgrado",
                    ),
                ),
                (
                    "otro_pregrado",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="",
                        null=True,
                        verbose_name="Otro pregrado",
                    ),
                ),
                (
                    "titulo_postgrado_ucv",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Titulo postgrado ucv",
                    ),
                ),
                (
                    "fecha_egreso_postgrado_ucv",
                    models.DateField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Fecha egreso postgrado ucv",
                    ),
                ),
                (
                    "universidad_postgrado_otra",
                    models.BooleanField(
                        default=False,
                        help_text="",
                        verbose_name="Universidad postgrado otra",
                    ),
                ),
                (
                    "fecha_egreso_postgrado_otra",
                    models.DateField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Fecha egreso postgrado otra",
                    ),
                ),
                (
                    "monto_aporte",
                    models.CharField(help_text="", verbose_name="Monto aporte"),
                ),
                (
                    "titulo_postgrado_otra",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Titulo postgrado otra",
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="empresa",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Sector",
                    ),
                ),
                (
                    "solicitar_seguro",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Solicitar seguro"
                    ),
                ),
                (
                    "egresado_postgrado_ucv",
                    models.BooleanField(
                        default=False,
                        help_text="",
                        verbose_name="Egresado postgrado ucv",
                    ),
                ),
                (
                    "medios_sociales",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Medios sociales",
                    ),
                ),
                (
                    "titulo_pregrado_otra",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Titulo pregrado otra",
                    ),
                ),
                (
                    "fecha_egreso_pregrado_ucv",
                    models.DateField(
                        help_text="",
                        max_length=255,
                        verbose_name="Fecha egreso pregrado ucv",
                    ),
                ),
                (
                    "facultad_pregrado_ucv",
                    models.CharField(
                        help_text="",
                        max_length=255,
                        verbose_name="Facultad pregrado ucv",
                    ),
                ),
                (
                    "empleado_externo",
                    models.BooleanField(
                        default=False,
                        help_text="",
                        max_length=255,
                        verbose_name="Empleado externo",
                    ),
                ),
                (
                    "pais_donde_trabaja",
                    models.CharField(
                        blank=True,
                        help_text="",
                        max_length=255,
                        null=True,
                        verbose_name="Pais donde trabaja",
                    ),
                ),
                (
                    "solicitar_td_caroni",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Solicitar TD Caroni"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Egresado",
                "verbose_name_plural": "Data Egresados",
                "unique_together": {("cedula", "prefijo_cedula")},
            },
        ),
    ]
