# Generated by Django 5.0.6 on 2024-05-27 20:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register", "0005_themespecprocarreer"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [
                            (
                                "paragraph",
                                wagtail.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                        "blockquote",
                                        "h2",
                                        "h3",
                                        "h4",
                                    ]
                                ),
                            )
                        ],
                        verbose_name="Descripción del trabajo",
                    ),
                ),
                (
                    "linkedin_link",
                    models.URLField(
                        blank=True,
                        help_text="Si esta oferta de trabajo está publicada en Linkedin puedes poner el link aquí",
                        null=True,
                        verbose_name="Link a la oferta en Linkedin",
                    ),
                ),
                (
                    "workplace",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "Presencial"),
                            ("HIBRID", "Híbrido"),
                            ("REMOTE", "Remoto"),
                        ],
                        max_length=255,
                        verbose_name="Tipo de Lugar de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta de trabajo",
                "verbose_name_plural": "Ofertas de trabajo",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="JobOfferIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indice de ofertas de trabajo",
                "verbose_name_plural": "Indices de ofertas de trabajo",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                ("web_page", models.URLField(verbose_name="Página web")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Negocio",
                "verbose_name_plural": "Negocios",
            },
        ),
        migrations.CreateModel(
            name="JobOfferInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.interesttheme",
                    ),
                ),
                (
                    "job_offer",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="business.joboffer",
                        verbose_name="Oferta de trabajo",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
