# Generated by Django 5.0.6 on 2024-10-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_jobssetup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
    ]
