# Generated by Django 5.0.6 on 2024-10-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0003_meta_options"),
        ("register", "0006_alter_registerapprovals_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentJobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de aplicación"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.joboffer",
                        verbose_name="Oferta de Trabajo",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
        ),
    ]
